# PASSWORD FLOW
requestPasswordReset:
  handler: src/handlers/password/request-password-reset/v1.handler
  events:
    - http:
        path: /user-management/password/request-reset
        method: POST
        cors: true

passwordReset:
  handler: src/handlers/password/reset-password/v1.handler
  events:
    - http:
        path: /user-management/password/reset
        method: POST
        cors: true

changePassword:
  handler: src/handlers/password/change-password/v1.handler
  events:
    - http:
        path: /user-management/password/change
        method: POST
        cors: true
