device-answer-challenge:
  handler: src/handlers/device/answer-challenge/v3.handler
  events:
    - http:
        path: /device/v3/enrollment/answer-challenge
        method: POST
        cors: true

device-check-if-trusted:
  handler: src/handlers/device/check-if-trusted/v3.handler
  events:
    - http:
        path: /device/v3/enrollment/check-device/{deviceId}
        method: GET
        cors: true
    - http:
        path: /device/v3/enrollment/check-device
        method: GET
        cors: true

device-confirm-enrollment:
  handler: src/handlers/device/confirm-enrollment/v3.handler
  events:
    - http:
        path: /device/v3/enrollment/confirm-enrollment
        method: POST
        cors: true

device-confirm-trusted-device:
  handler: src/handlers/device/confirm-trusted-device/v3.handler
  events:
    - http:
        path: /device/v3/enrollment/confirm-trust-device
        method: POST
        cors: true

device-initiate-enrollment:
  handler: src/handlers/device/initiate-enrollment/v3.handler
  events:
    - http:
        path: /device/v3/enrollment/initiate
        method: POST
        cors: true

device-initiate-otp-challenge:
  handler: src/handlers/device/initiate-otp-challenge/v3.handler
  events:
    - http:
        path: /device/v3/enrollment/initiate-challenge
        method: POST
        cors: true

device-untrust:
  handler: src/handlers/device/untrust/v3.handler
  events:
    - http:
        path: /device/v3/enrollment/{deviceId}/untrust
        method: PATCH
        cors: true

verify-in-app:
  handler: src/handlers/device/totp-validate/v3.handler
  events:
    - http:
        path: /verify/in-app-otp
        method: POST
        cors: true
