const Enum = require('enum');

const httpResponseCodes = new Enum({
  VALID: 'VALID',
  CREATE_RECORD_SUCCESS: 'CREATE_RECORD_SUCCESS',
  UPDATE_RECORD_SUCCESS: 'UPDATE_RECORD_SUCCESS',
  DELETE_RECORD_SUCCESS: 'DELETE_RECORD_SUCCESS',
  PROCESS_RECORD_SUCCESS: 'PROCESS_RECORD_SUCCESS',
  RETRIEVE_RECORD: 'RETRIEVE_RECORD',
  RETRIEVE_RECORD_LIST: 'RETRIEVE_RECORD_LIST',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  ERROR_PROCESSING: 'ERROR_PROCESSING',
  DATA_PROCESSING_ERROR: 'DATA_PROCESSING_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',

  DEVICE_EXIST: 'DEVICE_EXIST',
  USER_EXIST: 'USER_EXIST',
  USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
  DEVICE_TRUSTED: 'DEVICE_TRUSTED',
  DEVICE_NOT_TRUSTED: 'DEVICE_NOT_TRUSTED',
  IN_APP_OTP_ENABLED: 'IN_APP_OTP_ENABLED',
  IN_APP_OTP_ALREADY_ENABLED: 'IN_APP_OTP_ALREADY_ENABLED',
  IN_APP_OTP_VERIFIED: 'IN_APP_OTP_VERIFIED',
  DEVICE_ADDED: 'DEVICE_ADDED',
  ACCESS_CODE_GENERATED: 'ACCESS_CODE_GENERATED',
  ACCESS_TOKEN_GENERATED: 'ACCESS_TOKEN_GENERATED',
  USER_DID_UPDATED: 'USER_DID_UPDATED',
  ONEKOSMOS_USER: 'ONEKOSMOS_USER',
  EMAIL_ADDRESS_DOES_NOT_EXIST: 'EMAIL_ADDRESS_DOES_NOT_EXIST',
  DEVICE_NOT_OWNED: 'DEVICE_NOT_OWNED',

  HAS_TRUSTED_DEVICE: 'HAS_TRUSTED_DEVICE',
  HAS_NO_TRUSTED_DEVICE: 'HAS_NO_TRUSTED_DEVICE',
  HEADERS_CANNOT_BE_PARSED: 'HEADERS_CANNOT_BE_PARSED',
  DEVICE_SESSION_INVALID: 'DEVICE_SESSION_INVALID',
  DEVICE_HAS_BEEN_TRUSTED: 'DEVICE_HAS_BEEN_TRUSTED',
  DEVICE_HAS_BEEN_UNTRUSTED: 'DEVICE_HAS_BEEN_UNTRUSTED',

  PASSWORD_RESET: 'PASSWORD_RESET_SUCCESSFULLY',
  PASSWORD_CRITERIA_DOES_NOT_MATCH: 'PASSWORD_CRITERIA_DOES_NOT_MATCH',
  PASSWORD_CANNOT_BE_SAME: 'PASSWORD_CANNOT_BE_SAME',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE_SUCCESSFULLY',
  MEMBERSHIP_UPDATED: 'MEMBERSHIP_UPDATED',

  LOGOUT_SUCCESSFUL: 'LOGOUT_SUCCESSFUL',

  USER_SUCCESSFULLY_REGISTERED: 'USER_SUCCESSFULLY_REGISTERED',

  TMX_DENY: 'TMX_DENY',
  TMX_PROCESS_ERROR: 'TMX_PROCESS_ERROR',

  USER_STATUS_UPDATED: 'USER_STATUS_UPDATED',
  USER_LOCKED: 'USER_LOCKED',
  USER_ACTIVE: 'USER_ACTIVE',
  IN_APP_OTP_INVALID: 'IN_APP_OTP_INVALID',
  ACCESS_CODE_EMPTY: 'ACCESS_CODE_EMPTY',
  NEED_CONFIRMATION: 'NEED_CONFIRMATION',
});

const authServiceResponseCodes = new Enum({
  PASSWORD_DO_NOT_MATCH: 'PASSWORD_DO_NOT_MATCH',
  VERIFIED: 'VERIFIED',
  PASSWORD_UPDATED: 'PASSWORD_UPDATED',

  LOGIN_MAX_ATTEMPTS: 'LOGIN_MAX_ATTEMPTS',
});

const jwtResponseCodes = new Enum({
  JWT_VERIFIED: 'JWT_VERIFIED',
  JWT_INVALID: 'JWT_INVALID',
  SESSION_REVOKED: 'SESSION_REVOKED',
  JWT_EXPIRED: 'JWT_EXPIRED',
});

const validationCodes = new Enum({
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  MISSING_FIELDS: 'MISSING_FIELDS',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  RECORD_ALREADY_EXISTS: 'RECORD_ALREADY_EXISTS',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
});

module.exports = {
  httpResponseCodes,
  authServiceResponseCodes,
  validationCodes,
  jwtResponseCodes,
};
